# Setup
title:        Qin Blog
tagline:      一个技术博客
baseurl:      "/QinBlog"
paginate:     1
locale:       "zh-CN"

# About/contact
author:
  name:       Author name
  url:        http://localhost/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# local web server
host: 0.0.0.0

# paginate
paginate: 1
paginate_path: "/QinBlog/page:num"
