# Setup
title:        Qin Blog
tagline:      一个技术博客
# url:          "https://wazsmwazsm.github.io" 
baseurl:      ""
paginate:     1
locale:       "zh-CN"


# About/contact
author:
  name:       MrQin
  url:        http://localhost/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# local web server
host: 0.0.0.0

# paginate
paginate: 1
paginate_path: "page:num"
